version: '3'

services:
  laravel_franken:
    container_name: laravel_franken
    image: image_laravel_franken
    build: 
      dockerfile: worker.dockerfile
      context: .
    ports:
      - 8001:8000
    env_file:
      - .env